### ISSUE TITLE
.MOD location 

### ISSUE THREAD

**Issue by git-tdos** [wiremas/spore#2]
Hi, 

I have issues loading the plug-in, what does the .mod file syntax does looks like exactly ? I've tried "+ spore any C:\spore 
[r] scripts: scripts"
like where the folder is installed, but It seems that it is not the right path.

Thank you !

**Comment by wiremas** [comment]
the path in the .mod file needs to point to the spore folder and the .mod file must be placed in the MAYA_MODULE_PATH (default on windows is something like <user dir>/Documents/maya/modules )
