### ISSUE TITLE
Undo clearing all spore content

### ISSUE THREAD

**Issue by mkolar** [wiremas/spore#5]
Quite often when we use undo operation, the whole spore content disappears (so we have to paint from scratch). This happens fairly randomly but very often and produces this error:

```
// Error: instance_data : Could not set points: Operation would generate null pointer //
```

Unfortunately for this one, we're struggling to create a reproducible simple scene. We'll keep trying and post it here if we're successful in isolating it. 

We also experience this on some spore nodes that have been created in previous Maya session and then just re-opened and worked on again.

**Comment by wiremas** [comment]
The problem should be solved now.
The reason was that a double click wasn't triggering the command's doIt method which
initializes the undo stack.
