### ISSUE TITLE
RuntimeError: spore nodes's inMesh plug is not connected

### ISSUE THREAD

**Issue by Narann** [wiremas/spore#8]
Repro step:

* Open Maya.
* Load spore plugin.
* Create polySphere (Create/Polygon Primitives/Sphere).
* Open Spore Manager (Spore/Spore Manager).
* Select the sphere and click on the "Create Spore" icon in the Spore Manager.
* In the Spore Manager, right click and do "Delete".
* Select the sphere and click on the "Create Spore" icon in the Spore Manager.
* Crash (see log below).

```python
[dispatcher] : [CRITICAL] - Uncaught exception:
Traceback (most recent call last):
  File "/spore/plug-ins/scripted/spore_node.py", line 572, in compute
    other_in_mesh = node_utils.get_connected_in_mesh(node.thisMObject())
  File "/spore/scripts/utils/node_utils.py", line 194, in get_connected_in_mesh
    raise RuntimeError('spore nodes\'s inMesh plug is not connected')
RuntimeError: spore nodes's inMesh plug is not connected
```
Looks like it's related to `sys._global_spore_tracking_dir` that keep created items without remove them:

```python
for k, v in sys._global_spore_tracking_dir.iteritems():
    print k, v
```
```
2460714976 <scripted.spore_node.SporeNode; proxy of <Swig Object of type 'MPxLocatorNode *' at 0x7f82dc0379c0> >
2460723312 <scripted.spore_node.SporeNode; proxy of <Swig Object of type 'MPxLocatorNode *' at 0x7f82dc037d20> >
3041226656 <scripted.spore_node.SporeNode; proxy of <Swig Object of type 'MPxLocatorNode *' at 0x7f82d6a66030> >
1858774048 <scripted.spore_node.SporeNode; proxy of <Swig Object of type 'MPxLocatorNode *' at 0x7f82d7844f00> >
```

Looks like the nodes tracking is not removed from the dict when nodes are removed.

Maya 2018.5, Linux.

**Comment by wiremas** [comment]
Thanks for the repro. As you described the entry was not properly removed from the dict upon node deletion. Should be [fixed](https://github.com/wiremas/spore/commit/d05ccbeff0b5ebc116702391c3daaf994e29851f) now.

**Comment by Narann** [comment]
Thanks @wiremas! I try the fix as soon as possible.

**Comment by Narann** [comment]
I just tested, this bug is fixed. Thanks again !

I have few other issues but will create separate tickets with repo steps. :)
